version: '3.3'
services:
  bountydns:
    depends_on:
      - db
      - broadcast
  dns:
    depends_on:
      - bountydns
      - broadcast
      - proxy
  proxy:
    depends_on:
      - webui
      - bountydns
