version: '3.3'
services:
  bountydns:
    build:
      context: ./../../
      dockerfile: ./infra/docker/bountydns.dockerfile
    image: 3lpsy/bountydns:latest
    networks:
      bountydnspub:
  dns:
    image: 3lpsy/bountydns:latest
    networks:
      bountydnspub:
  webui:
    build:
      context: ./../../bountydns
      dockerfile: ./../infra/docker/webui.dockerfile
    image: 3lpsy/bountydns-webui:latest
    networks:
      bountydnspub:
  proxy:
    build:
      context: ./../proxy
      dockerfile: ./../docker/proxy.dockerfile
    image: 3lpsy/bountydns-proxy:latest
    networks:
      bountydnspub:
  broadcast:
    build:
      context: ./../broadcast
      dockerfile: ./../docker/broadcast.dockerfile
    image: 3lpsy/bountydns-broadcast:latest
    networks:
      bountydnspub:
  db:
    image: postgres:latest
    networks:
      bountydnspub:
  # dbui:
  #   image: dpage/pgadmin4
  # search:
  #   image: amazon/opendistro-for-elasticsearch:latest
